name: hourly-cron
on:
  schedule:
    - cron: '1,16,31,46 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
            --url 'https://trading-straregy.vercel.app/api/larkRobotInteraction' \
            --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
