name: Send request to website

on:
  schedule:
    - cron: "0,15,30,45 * * * *" # every 15 minutes

jobs:
  send-request:
    runs-on: ubuntu-latest
    steps:
      - name: Send GET request to lark robot api
        run: curl -s -o /dev/null -w %{http_code} "${{ secrets.LARK_ROBOT_URL }}"
