name: Trigger post

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  trigger-function:
    runs-on: ubuntu-latest
    steps:
      - name: HTTP Request Action
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://trading-straregy.vercel.app/api/larkRobotInteraction'
          method: 'POST'
          data: '{"key":"${{secrets.BEARER_TOKEN}}"}'
