name: Trigger post

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  trigger-function:
    runs-on: ubuntu-latest
    steps:
      - name: HTTP Request Action
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://trading-strategy.vercel.app/api/larkRobotInteraction'
          method: 'POST'
          headers: '{"Content-Type": "application/json"}'
          body: '{"key": ${{ secrets.TRIGGER_ALARM_SYSTEM_KEY }}}'
