name: Send request to website

on:
  schedule:
    - cron: "*/15 * * * *" # every 15 minutes

jobs:
  send-request:
    runs-on: ubuntu-latest
    steps:
      - name: Send GET request to nextjs api
        run: curl https://your-nextjs-api-url.com
