name: Send HTTP request to website

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  trigger-function:
    runs-on: ubuntu-latest
    steps:
      - name: HTTP Request Action
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://contract-monitor-dev.vercel.app/'
          method: 'GET'
